# Generated by Django 5.0.7 on 2024-10-21 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facultyapp', '0003_alter_marks_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marks',
            name='course',
            field=models.CharField(choices=[('PFSD', 'Python FUll Stack Development'), ('AOOP', 'Advanced Object Oriented Programming')], max_length=50),
        ),
    ]
