# Generated by Django 5.1.2 on 2024-11-05 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facultyapp', '0005_alter_marks_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marks',
            name='course',
            field=models.CharField(choices=[('PFSD', 'Python FUll Stack Development'), ('AOOP', 'Advanced Object Oriented Programming')], max_length=50),
        ),
    ]
