# Generated by Django 5.1.2 on 2024-11-12 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facultyapp', '0006_alter_marks_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marks',
            name='course',
            field=models.CharField(choices=[('AOOP', 'Advanced Object Oriented Programming'), ('PFSD', 'Python FUll Stack Development')], max_length=50),
        ),
    ]
